version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.11.0
    - 0.11.1
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.14
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.8
    - 0.11.9
    - 0.9.0
  - dependency-name: source-map
    versions:
    - 0.7.3
  - dependency-name: playwright-core
    versions:
    - 1.10.0
    - 1.8.1
    - 1.9.0
    - 1.9.1
    - 1.9.2
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: husky
    versions:
    - 5.0.9
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
  - dependency-name: delay
    versions:
    - 5.0.0
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
